# Alacritty Configuration
# Import Catppuccin theme
general.import = [
    "catppuccin-mocha.toml"
]

# Window settings
[window]
opacity = 0.95
decorations = "none"
startup_mode = "Windowed"
dynamic_title = true

[window.padding]
x = 0
y = 0

# Font configuration
[font]
# Primary font - choose one of these options:
normal = { family = "UbuntuMono Nerd Font", style = "Regular" }
# normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
# normal = { family = "FiraCode Nerd Font", style = "Regular" }
# normal = { family = "Hack Nerd Font", style = "Regular" }

bold = { family = "UbuntuMono Nerd Font", style = "Bold" }
italic = { family = "UbuntuMono Nerd Font", style = "Italic" }
bold_italic = { family = "UbuntuMono Nerd Font", style = "Bold Italic" }

size = 11.8

# Selection and clipboard
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# Cursor
[cursor]
style = "Block"
unfocused_hollow = true

# Terminal settings
[terminal]
shell = "tmux"
# shell = { program = "tmux", args = ["new-session", "-A", "-s", "main"] }

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Mouse - disable for keyboard-only workflow
[mouse]
hide_when_typing = true

# Key bindings for keyboard-driven workflow
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

# Vi mode for text selection (like vim visual mode)
[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
action = "ToggleViMode"

# Search functionality
[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

# Scrollback navigation
[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "U"
mods = "Control|Shift"
action = "ScrollHalfPageUp"

[[keyboard.bindings]]
key = "D"
mods = "Control|Shift"
action = "ScrollHalfPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Control|Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Control|Shift"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

# Environment variables
[env]
TERM = "alacritty"
